name: snmp
description: A starting point for Dart SNMP protocol, for Using IP(network) to Easyly access snmp data.
version: 0.0.1
homepage: https://gitee.com/almpazel/dart-snmp.git

## export http_proxy=socks5h://localhost:1080
## export https_proxy=socks5h://localhost:1080
## pub publish --server=https://pub.dartlang.org -v

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  convert: ^2.1.1
  logger: ^0.9.2

dev_dependencies:
  test: ^1.14.4
